# Dil seçimi ayarı
language: "en"  # "tr" veya "en" gibi desteklenen dillerden biri
# Market fiyat ayarları
prices:
  coal: 5.0
  iron_ingot: 20.0
  gold_ingot: 35.0
  diamond: 200.0
  emerald: 250.0
  netherite_ingot: 1000.0
  copper_ingot: 12.0
  redstone: 4.0
  lapis_lazuli: 15.0
  quartz: 8.0
  wheat: 3.0
  potato: 3.0
  carrot: 3.0
  beetroot: 3.0
  melon_slice: 0.3
  pumpkin: 0.5
  sugar_cane: 0.1
  bamboo: 0.05
  cactus: 0.1
  apple: 2.0
  rotten_flesh: 0.3
  bone: 0.5
  string: 0.5
  spider_eye: 1.0
  gunpowder: 1.5
  feather: 0.5
  leather: 1.0
  rabbit_foot: 2.0
  mutton: 1.0
  beef: 1.0
  cod: 1.0
  salmon: 1.0
  tropical_fish: 1.5
  pufferfish: 1.5
  chicken: 1.0
  porkchop: 1.0
  cooked_chicken: 2.0
  cooked_porkchop: 2.0
  kelp: 0.1
  sea_pickle: 0.5
  prismarine_shard: 3.0
  prismarine_crystals: 4.0
  nautilus_shell: 6.0
  heart_of_the_sea: 25.0
  nether_wart: 2.0
  glow_berries: 1.0
  sweet_berries: 1.0
  cocoa_beans: 1.0
  chorus_fruit: 1.0

# Fiyat dalgalanma ayarları
price_fluctuation:
  enabled: true
  interval_minutes: 1
  max_change_percentage: 50
